services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    command: start --log trace --user root --pass root memory
    ports:
      - "8001:8000"   # HTTP
      - "8002:8001"   # WebSocket
    volumes:
      - surreal-data:/var/lib/surrealdb

  server:
    build: .
    container_name: sentient-brain-surreal-server
    env_file:
      - .env
    ports:
      - "8010:8000"
    volumes:
      - ./:/app
    depends_on:
      - surrealdb
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  surreal-data:
